### ISSUE TITLE
Add WKWebView for iOS8 devices

### ISSUE THREAD

**Issue by nabilfreeman** [nabilfreeman/ios-universal-webview-boilerplate#1]
Apparently WKWebView has must better performance than UIWebView as it has the same power as native Safari...

**Comment by Haroenv** [comment]
Which in iOS 9 will be even a lot better (and actually basically Safari)

https://developer.apple.com/videos/wwdc/2015/?id=504

**Comment by alex3165** [comment]
I just PR the project for WKWebView support when iOS is up to 8.0, never done before but it seems works.

**Comment by nabilfreeman** [comment]
closed by #3!
