### ISSUE TITLE
Internet mode doesn't work

### ISSUE THREAD

**Issue by MohanL** [nabilfreeman/ios-universal-webview-boilerplate#8]
let url: NSURL = NSURL (string: "http://google.com")!;
I changed the url to be this and commented out the previous url declaration. the program doesn't work

**Comment by nabilfreeman** [comment]
hey @MohanL, does it work when you remove the space here: `NSURL (string:`?

**Comment by gybin02** [comment]
I remove the space ,but it still no work ..  the app now is white blank

**Comment by gybin02** [comment]
```
     let url: NSURL = NSURL(string: "http://www.baidu.com")!
```

I even write this agiain

**Comment by gybin02** [comment]
I found you must use https .

**Comment by nabilfreeman** [comment]
Hey @gybin02, that's so weird! Thanks a lot for figuring it out :) I wonder if it's because a previous contribution changed the webview to use WKWebView rather than the regular one. I will do more investigating when I have more free time. I hope it works for you with using `https` for now...

**Comment by teolemon** [comment]
You can add an exemption in Info.plist
http://stackoverflow.com/questions/31254725/transport-security-has-blocked-a-cleartext-http

**Comment by nabilfreeman** [comment]
Thanks for marking as resolved! 👍
